---
title: "R Notebook analysing Kaggle results"
output: html_notebook
---

Load the required libraries
```{r, echo=FALSE}
library(tidyverse)
```
Reading and cleaning the data
```{r}
#Read the csv
multch <- read.csv("/Users/Ronak Shah/Downloads/multipleChoiceResponses.csv", header = TRUE)
```

Plot top 5 countries participated in the survey
```{r}
multch %>%
  slice(-1) %>%
  count(Q3) %>%
  top_n(5, n) %>%
  ggplot() + 
    aes(Q3, n) + 
    geom_bar(stat = "identity") + 
  xlab("Country") + ylab("Count") + 
  ggtitle("Count of respondents by country")

```

Find out the male-female ratio
```{r}

multch %>%
  slice(-1) %>%
  count(Q1) %>%
  ggplot() + 
  aes(Q1, n, fill = n) + 
  geom_bar(stat = "identity") + 
  scale_fill_identity() + 
  xlab("Gender") + ylab("Count") + 
  ggtitle("Gender count")
```

Male and Female ratio for top 5 countries

```{r}
multch %>%
  slice(-1) %>%
  filter(Q1 %in% c("Male", "Female")) %>%
  count(Q3, Q1) %>%
  spread(Q1,n) %>%
  arrange(desc(Male)) %>%
  head() %>%
  gather(Country, Value, -Q3) %>%
  ggplot() + 
  aes(Q3, Value) + 
  geom_bar(aes(fill = Country), stat = "identity")
```